name: Rust + Anchor CI
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  build-and-test:
    runs-on: codeberg-medium
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Cargo registry + git + target
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
        key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: cargo-${{ runner.os }}-

      - name: Install Solana CLI (latest stable, non-interactive)
        run: |
          curl --proto '=https' --tlsv1.2 -sSfL https://solana-install.solana.workers.dev | bash -s -- --no-modify-path
          export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH 

      - name: Create Non-Ineractive CI Wallet
        run: |
          mkdir -p ~/.config/solana
          echo "[keypair]" > ~/.config/solana/cli/config.yml
          echo "json_rpc_url = \"http://127.0.0.1:8899\"" >> ~/.config/solana/cli/config.yml
          echo "websocket_url = \"ws://127.0.0.1:8900\"" >> ~/.config/solana/cli/cofig.yml
          echo "keypair_path = \"$HOMNE/.config/solana/id.json\"" >> ~/.config/solana/cli/comfig.yml
          solana-keygen new  --no-passphrase --silent --outfile ~/.config/solana/id.json

      - name: Verify versions
        run: |
          rustc --version
          cargo --version
          solana --version
          anchor --version

      - name: Build and Test 
        run: |
          anchor build
          anchor test
