name: Rust + Anchor CI
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  build-and-test:
    runs-on: codeberg-medium
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Cargo registry + git + target
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
        key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: cargo-${{ runner.os }}-

      - name: Install Solana CLI (latest v1 stable)
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/stable/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: Install Anchor (0.30.1 - latest as of 2026)
        run: |
          cargo install --git https://github.com/coral-xyz/anchor anchor-cli --locked --tag v0.30.1
          echo "$HOME/.cargo/bin" >> $GITHUB_PATh

      - name: Verify versions
        run: |
          rustc --version
          cargo --version
          solana --version
          anchor --version

      - name: Test
        run: cargo test-bpf -- --nocapture
