name: Rust + Anchor CI
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  build-and-test:
    runs-on: codeberg-medium
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Cargo registry + git + target
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
        key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: cargo-${{ runner.os }}-

      - name: Install Solana and Anchor
        uses: metadaoproject/setup-solana@v1
        with:
          solana-cli-version: latest
          anchor-version: '0.32.1'

      - name: Verify versions
        run: |
          rustc --version
          cargo --version
          solana --version
          anchor --version

      - name: Test
        run: cargo test-bpf -- --nocapture
